kibot:
  version: 1

preflight:
  run_erc: true
  update_xml: true
  run_drc: true
  check_zone_fills: true
  ignore_unconnected: false
  filters:
  - filter: 'Ignore silk over NPTH'
    error: 'silk_over_copper'
    regex:  'Through hole pad'

import:
  - ../../config/docs.kibot.yaml
  - ../../config/renders.kibot.yaml
  - ../../config/manufacturers/PCBWay.kibot.yaml
