kibot:
  version: 1

preflight:
  run_erc: true
  update_xml: true
  run_drc: true
  check_zone_fills: true
  ignore_unconnected: false

outputs:
  - name: gerbers_pcbway
    comment: Gerbers with names compatible with KiCad
    type: gerber
    dir: output/gerbers/pcbway
    options: &gerber_options
      exclude_edge_layer: true
      exclude_pads_from_silkscreen: true
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: true
      force_plot_invisible_refs_vals: false
      tent_vias: true
      use_protel_extensions: true
      create_gerber_job_file: false
      output: "%f-%i%v.%x"
      gerber_precision: 4.6
      use_gerber_x2_attributes: false
      use_gerber_net_attributes: false
      disable_aperture_macros: true
      line_width: 0.1
      subtract_mask_from_silk: false
      inner_extension_pattern: '.gl%N'
    layers:
      - copper
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - F.Paste
      - B.Paste
      - Edge.Cuts

  - name: drill_pcbway
    comment: Drill files
    type: excellon
    dir: output/gerbers/pcbway
    options:
      metric_units: false
      minimal_header: true
      zeros_format: SUPPRESS_LEADING
      left_digits: 3
      right_digits: 3
      pth_and_npth_single_file: false
      pth_id: ''
      npth_id: '-NPTH'
      output: "%f%i.drl"

  - name: bom
    comment: Bill of Materials
    type: bom
    dir: output/docs
    options:
      format: HTML
      html:
        title: ESP-32 Board Bill of Materials
        col_colors: false
        logo: false

  - name: sch_pdf
    comment: Schematic PDF print
    type: pdf_sch_print
    dir: output/docs

  - name: pcb_pdf
    comment: PCB PDF print
    type: pdf_pcb_print
    dir: output/docs
    layers: all


  - name: sch_svg
    comment: Schematic SVG print
    type: svg_sch_print
    dir: output/docs/svg/schematic

  - name: pcb_svg
    comment: PCB SVG print
    type: svg
    dir: output/docs/svg/pcb
    layers: all

  - name: pcb_2d_top
    comment: 2D model of PCB
    type: pcbdraw
    dir: output/docs/render
    options:
      bottom: false
      show_components: all

  - name: pcb_2d_bottom
    comment: 2D model of PCB
    type: pcbdraw
    dir: output/docs/render
    options:
      bottom: true
      show_components: all

  - name: pcb_3d
    comment: 3D model of PCB
    type: step
    dir: output/docs/render